// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One command sent through a terminal session. `host_id` is `None` for
 * local-terminal sessions (no remote target).
 */
export type CommandHistoryEntry = { id: bigint, host_id: string | null, command: string, used_at: string, };
