// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single entry returned by an SFTP listing.
 *
 * `size`, `mtime` and `permissions` are absent when the SFTP server doesn't
 * expose them (rare, but allowed by the protocol).
 */
export type FileEntry = { 
/**
 * Bare name of the file (no leading path).
 */
name: string, 
/**
 * True when the entry is a directory (after symlink resolution by SFTP).
 */
is_dir: boolean, is_symlink: boolean, size: bigint | null, 
/**
 * Modification time as RFC 3339 UTC, or `None` when not provided.
 */
mtime: string | null, 
/**
 * Unix-style permission bits (lower 12 bits), `None` when not provided.
 */
permissions: number | null, };
