// This file was generated by ts-rs. Do not edit manually.
// Source: src-tauri/src/models/group.rs

export type Group = {
  id: string;
  name: string;
  parent_id: string | null;
  position: number;
  created_at: string;
  updated_at: string;
};
