// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating or updating a [`Group`].
 */
export type GroupInput = { name: string; parent_id: string | null; position: number };
