// This file was generated by ts-rs. Do not edit manually.
// Source: src-tauri/src/models/host.rs

export type HostInput = {
  label: string;
  hostname: string;
  port: number;
  username: string;
  group_id: string | null;
};
