// This file was generated by ts-rs. Do not edit manually.
// Source: src-tauri/src/models/host.rs

export type Host = {
  id: string;
  label: string;
  hostname: string;
  port: number;
  username: string;
  group_id: string | null;
  created_at: string;
  updated_at: string;
};
