// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating or updating a [`Host`]. `id` is server-generated on create.
 */
export type HostInput = { label: string, hostname: string, port: number, username: string, group_id: string | null, proxy_jump_host_id: string | null, identity_id: string | null, agent_forward: boolean, log_to_file: boolean, pre_connect_script: string, post_connect_script: string, };
