// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * (host_id, tag_id) pair returned by the join query so the UI can build the
 * host → tags map without re-querying per host.
 */
export type HostTagLink = { host_id: string, tag_id: string, };
