// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * (host_id, key_id, priority) row from the `host_keys` join table.
 */
export type HostKeyLink = { host_id: string, key_id: string, priority: number, };
