// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `(identity_id, key_id, priority)` join row, returned by the front so it
 * can render and reorder the key list without an extra query.
 */
export type IdentityKeyLink = { identity_id: string, key_id: string, priority: number, };
