// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reusable SSH connection profile (P4-T05). A host can reference one of
 * these and inherit `username`, `agent_forward`, and the priority-ordered
 * list of keys instead of duplicating them across every entry.
 */
export type Identity = { id: string, name: string, username: string, agent_forward: boolean, created_at: string, updated_at: string, };
