// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One stored TOFU fingerprint for an (hostname, port) endpoint.
 */
export type KnownHost = { hostname: string, port: number, fingerprint: string, key_type: string, accepted_at: string, };
