// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ForwardType } from "./ForwardType";

/**
 * Payload for creating or updating a [`PortForward`].
 */
export type PortForwardInput = { host_id: string, forward_type: ForwardType, label: string, local_port: number, remote_host: string, remote_port: number, auto_start: boolean, };
