// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A persisted port-forward definition. The runtime state (whether the
 * listener is currently active) lives outside the DB in `ForwardRegistry`.
 */
export type PortForward = { id: string, host_id: string, 
/**
 * Stored as a String so sqlx can hydrate the row; convert via
 * [`ForwardType::parse`] when needed.
 */
forward_type: string, label: string, local_port: number, remote_host: string, remote_port: number, auto_start: boolean, created_at: string, };
