// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SnippetInput = { name: string, content: string, folder: string | null, tags_csv: string, variables_schema_json: string, };
