// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A reusable command (or sequence) the user can fire into a terminal.
 *
 * `content` may include `{{variable}}` placeholders. Built-in variables —
 * `{{host}}`, `{{user}}`, `{{date}}` — are substituted automatically; any
 * other `{{custom}}` triggers a prompt in the UI before insertion.
 */
export type Snippet = { id: string, name: string, content: string, 
/**
 * Optional folder label used to group snippets in the palette.
 */
folder: string | null, 
/**
 * Comma-separated free-form tags (lowercase, trimmed).
 */
tags_csv: string, 
/**
 * JSON array of `{ name, default? }` describing custom variables. May be `"[]"`.
 */
variables_schema_json: string, created_at: string, updated_at: string, };
