// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshConfigImportEntry } from "./SshConfigImportEntry";

/**
 * Result of an import preview: the parsed entries paired with whether a host
 * with the same label already exists in the database (so the UI can warn).
 */
export type SshConfigImport = { path: string, entries: Array<SshConfigImportEntry>, };
