// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SshConfigImportEntry = { 
/**
 * True iff a host with the same label already exists.
 */
duplicate: boolean, alias: string, hostname: string | null, user: string | null, port: number | null, identity_file: string | null, proxy_jump: string | null, };
