// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single importable SSH host derived from `~/.ssh/config`.
 *
 * Every field except `alias` is optional because OpenSSH defaults kick in
 * when a directive is omitted (e.g. port 22, user = current OS user).
 */
export type SshConfigEntry = { alias: string, hostname: string | null, user: string | null, port: number | null, identity_file: string | null, proxy_jump: string | null, };
