// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Algorithms exposed to the front for the "generate key" form.
 */
export type SshKeyAlgorithm = "ed25519" | "rsa4096";
