// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metadata about an SSH key stored in this app. The actual private key file
 * lives on disk (`private_key_path`); its optional passphrase is stored in
 * the OS keychain (`ssh-key-{id}`).
 */
export type SshKey = { id: string, name: string, 
/**
 * "ed25519", "rsa-3072", "rsa-4096", "ecdsa-256", ...
 */
key_type: string, 
/**
 * OpenSSH-format public key (single-line, e.g. `ssh-ed25519 AAA... user@host`).
 */
public_key: string, 
/**
 * SHA-256 fingerprint formatted `SHA256:<base64>`.
 */
fingerprint: string, private_key_path: string, has_passphrase: boolean, created_at: string, };
