// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Résultat compact d'un push ou pull, pour feedback côté front.
 */
export type SyncResult = { 
/**
 * Sha du commit local après l'opération (push) ou du remote après pull.
 */
head_sha: string | null, 
/**
 * `true` si le vault distant a vraiment changé par rapport à la
 * dernière opération.
 */
changed: boolean, 
/**
 * Message court lisible côté UI.
 */
summary: string, };
