// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration et état runtime de la sync Git (P5-T03 → T05).
 *
 * `auth_method` accepte :
 *   - `"none"` : URL publique
 *   - `"https-pat"` : Personal Access Token stocké dans le keychain OS
 *   - `"ssh"` : utilise la config SSH du système (clé par défaut, agent)
 *
 * Tous les champs `last_*` sont du best-effort : si le push échoue, on
 * stocke `last_error` mais on ne perd pas la config.
 */
export type SyncState = { repo_url: string, branch: string, auth_method: string, enabled: boolean, last_remote_sha: string | null, last_pushed_at: string | null, last_pulled_at: string | null, last_error: string | null, };
