// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SyncConfigInput = { repo_url: string, branch: string, auth_method: string, enabled: boolean, };
