// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A colored label that can be attached to multiple hosts.
 */
export type Tag = { id: string, name: string, color: string, created_at: string, };
