// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Payload for creating or renaming a [`Tag`].
 */
export type TagInput = { name: string, color: string, };
