// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A remote SSH endpoint persisted in the local database.
 */
export type Host = { id: string, label: string, hostname: string, port: number, username: string, group_id: string | null, created_at: string, updated_at: string, };
